export const uocMaterialsMap: Record<string, string> = {
  "internal-correspondence": "https://materials.campus.uoc.edu/continguts/PID_00262780/index.html",
  "invitations-suggestions-complaints": "https://materials.campus.uoc.edu/continguts/PID_00262777/index.html",
  "invitations-suggestions-and-complaints": "https://materials.campus.uoc.edu/continguts/PID_00262777/index.html",
  "telephone-skills": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00262776/index.html",
  "videoconference-and-discussions": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00262779/index.html",
  "trade-and-commerce": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269010/index.html",
  "our-natural-world": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269014/index.html",
  "news-and-current-affairs": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269013/index.html",
  "visitors-and-guests": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00262781/index.html",
  email: "https://materials.campus.uoc.edu/continguts/PID_00262783/index.html",
  "getting-down-to-business": "https://materials.campus.uoc.edu/continguts/PID_00262772/index.html",
  "getting-the-ball-rolling": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00257629/index.html",
  "wrapping-it-up": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00262773/index.html",
  "the-body-of-a-presentation": "https://materials.campus.uoc.edu/continguts/PID_00262778/index.html",
  "the-end-of-a-presentation": "https://materials.campus.uoc.edu/continguts/PID_00262775/index.html",
  "the-introduction-to-a-presentation": "https://materials.campus.uoc.edu/continguts/PID_00262774/index.html",
  lifestyles: "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269030/index.html",
  "arts-and-culture": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269031/index.html",
  film: "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269027/index.html",
  "our-global-world": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269029/index.html",
  "scientific-development": "https://aprenentatge.recursos.uoc.edu/continguts/PID_00269028/index.html",
};
